### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by bradlet** [bradlet/broadboards#8]
## Description
This is sort-of an EPIC card. Just going to list all the UI components I can think of here so we have them written down.

- [x] Header with navbar, icon and website name [A]
- [x] Main content section [B]
- [ ] Aside with some info (group info, search bar, user info?) [C]
- [ ] Footer with important links or legal statements (Like our IP rights? Idk?) [D]
- [x] Login Page [E]

**Comment by cteters** [comment]
- [ ] Display changing features, such as altering the color scheme and the grid alignment for the feed [F]

**Comment by cteters** [comment]
Covering (A) & (F)

**Comment by bradlet** [comment]
Covering (B)

**Comment by SulimanCS** [comment]
The main content section mainly is done, just needs more polish

**Comment by SulimanCS** [comment]
The login page is also done
